// EN/RU strings for the SPA — originally ported from the Phase 20 WebStrings.cs
// (since removed along with the Razor UI), so this is now the only UI string
// table: the backend carries none.
type Dict = Record<string, string>

export const EN: Dict = {
  'Login.Subtitle': 'Sign in to the web console',
  'Login.Username': 'Username',
  'Login.Password': 'Password',
  'Login.SignIn': 'Sign in',
  'Login.Error': 'Invalid username or password.',

  'Nav.Cameras': 'Cameras',
  'Nav.Grid': 'Grid',
  'Nav.Groups': 'Groups',
  'Nav.Discovery': 'Discovery',
  'Nav.System': 'System',
  'Nav.SignOut': 'Sign out',

  'System.Title': 'System',
  'System.Version': 'Version',
  'System.Cameras': 'Cameras',
  'System.Groups': 'Groups',
  'System.Sessions': 'Active sessions',
  'System.Streams': 'Live streams',
  'System.Backup': 'Backup & restore',
  'System.Export': '⭳ Export config',
  'System.ImportBtn': 'Import',
  'System.BackupNote':
    'Export writes a JSON backup of cameras, groups and layouts. Camera passwords are never included.',
  'System.Imported': 'Imported:',
  'System.ImportError': 'Import failed — check the file.',
  'System.SessionsTitle': 'Sessions',
  'System.RevokeAll': 'Sign out all sessions',
  'System.RevokeConfirm': 'Sign out every session, including this one?',

  'Cameras.Title': 'Cameras',
  'Cameras.Add': '＋ Add camera',
  'Cameras.Empty': 'No cameras yet.',
  'Common.Loading': 'Loading…',
  'Common.Save': 'Save',
  'Common.Cancel': 'Cancel',
  'Common.Close': 'Close',
  'Cameras.Th.Name': 'Name',
  'Cameras.Th.Host': 'Host',
  'Cameras.Th.Group': 'Group',
  'Cameras.Th.Grid': 'Grid',
  'Cameras.Live': '▶ Live',
  'Cameras.Edit': 'Edit',
  'Cameras.Delete': 'Delete',
  'Cameras.DeleteConfirm': 'Delete this camera?',
  'Common.Yes': 'yes',
  'Common.No': 'no',

  'Editor.AddTitle': 'Add camera',
  'Editor.EditTitle': 'Edit camera',
  'Editor.Error':
    'Please check the fields — name, host and a valid RTSP URL are required.',
  'Editor.Name': 'Name',
  'Editor.Host': 'Host',
  'Editor.RtspMain': 'RTSP main URL',
  'Editor.RtspSub': 'RTSP sub URL (optional)',
  'Editor.HttpPort': 'HTTP port',
  'Editor.OnvifPort': 'ONVIF port',
  'Editor.Group': 'Group',
  'Editor.NoGroup': '(no group)',
  'Editor.Quality': 'Stream quality',
  'Editor.Username': 'Username',
  'Editor.Password': 'Password',
  'Editor.KeepBlank': 'leave blank to keep',
  'Editor.Optional': 'optional',
  'Editor.Save': 'Save',
  'Editor.Add': 'Add camera',
  'Editor.Cancel': 'Cancel',

  'Grid.Title': 'Grid',
  'Grid.Empty': 'No cameras to show. Add cameras or include them in the grid.',
  'Grid.NewLayout': '＋ Layout',
  'Grid.NewLayoutTitle': 'New layout',
  'Grid.NewLayoutName': 'New layout name',
  'Grid.Edit': 'Edit layout',
  'Grid.Rename': 'Rename',
  'Grid.DeleteLayout': 'Delete layout',
  'Grid.DeleteLayoutConfirm': 'Delete this layout?',
  'Grid.Size': 'Size',
  'Grid.EmptyCell': '(empty)',
  'Grid.NoLayouts': 'No layouts yet — create one.',
  'Grid.Single': 'Single camera',
  'Grid.PrevPage': 'Previous page',
  'Grid.NextPage': 'Next page',
  'Grid.EditingPage': 'Editing page',

  'Groups.Title': 'Groups',
  'Groups.Add': '＋ Add group',
  'Groups.Name': 'Name',
  'Groups.NewName': 'Group name',
  'Groups.Empty': 'No groups yet.',
  'Groups.Rename': 'Rename group',
  'Groups.DeleteConfirm': 'Delete this group?',
  'Groups.InUse': 'Group is still used by cameras.',
  'System.Account': 'Account',

  'Live.Back': '← Cameras',
  'Camera.Details': 'Details',
  'Camera.Credentials': 'Credentials set',
  'Camera.Capabilities': 'Capabilities',
  'Camera.Chip': 'Chip',
  'Camera.Firmware': 'Firmware',

  'Ptz.Title': 'PTZ control',
  'Ptz.Up': 'Up',
  'Ptz.Down': 'Down',
  'Ptz.Left': 'Left',
  'Ptz.Right': 'Right',
  'Ptz.UpLeft': 'Up-left',
  'Ptz.UpRight': 'Up-right',
  'Ptz.DownLeft': 'Down-left',
  'Ptz.DownRight': 'Down-right',
  'Ptz.Stop': 'Stop',
  'Ptz.Zoom': 'Zoom',
  'Ptz.ZoomIn': 'Zoom in',
  'Ptz.ZoomOut': 'Zoom out',
  'Ptz.Speed': 'Speed',
  'Ptz.Presets': 'Presets',
  'Ptz.PresetName': 'New preset',
  'Ptz.PresetSave': 'Save',
  'Ptz.PresetDelete': 'Delete preset',
  'Ptz.Error': 'The camera did not accept the PTZ command.',

  'Discovery.Title': 'Discovery',
  'Discovery.Scan': 'Scan',
  'Discovery.Stop': 'Stop',
  'Discovery.DeepScan': 'Deep scan',
  'Discovery.DeepScanNote':
    'Passive sources (ONVIF, mDNS) always run. Deep scan also sweeps the local subnet — it finds cameras that announce nothing, but looks like a port scan on the network.',
  'Discovery.Scanning': 'Scanning…',
  'Discovery.Found': 'Found:',
  'Discovery.Nothing': 'Nothing answered. Try a deep scan, or add the camera by hand.',
  'Discovery.Cancelled': 'Scan cancelled.',
  'Discovery.Failed': 'Scan failed.',
  'Discovery.Busy': 'A scan is already running.',
  'Discovery.Th.Device': 'Device',
  'Discovery.Th.Host': 'Address',
  'Discovery.Th.Signals': 'Found via',
  'Discovery.Confidence.High': 'identified',
  'Discovery.Confidence.Medium': 'probably a camera',
  'Discovery.Confidence.Low': 'maybe',
  'Discovery.AlreadyAdded': 'already added',
  'Discovery.Add': 'Add',
  'Discovery.AddTitle': 'Add camera',
  'Discovery.Probe': 'Probe',
  'Discovery.ProbeFirst': 'probe, or type the RTSP URL',
  'Discovery.ProbeFailed': 'Probe failed.',
  'Discovery.NoOnvif': 'No ONVIF answer — check the login, or add it with the RTSP URL below.',
  'Discovery.AddFailed': 'Could not add the camera.',
}

export const RU: Dict = {
  'Login.Subtitle': 'Вход в веб-консоль',
  'Login.Username': 'Логин',
  'Login.Password': 'Пароль',
  'Login.SignIn': 'Войти',
  'Login.Error': 'Неверный логин или пароль.',

  'Nav.Cameras': 'Камеры',
  'Nav.Grid': 'Сетка',
  'Nav.Groups': 'Группы',
  'Nav.Discovery': 'Поиск',
  'Nav.System': 'Система',
  'Nav.SignOut': 'Выход',

  'System.Title': 'Система',
  'System.Version': 'Версия',
  'System.Cameras': 'Камеры',
  'System.Groups': 'Группы',
  'System.Sessions': 'Активные сессии',
  'System.Streams': 'Живые потоки',
  'System.Backup': 'Бэкап и восстановление',
  'System.Export': '⭳ Экспорт конфига',
  'System.ImportBtn': 'Импорт',
  'System.BackupNote':
    'Экспорт пишет JSON-бэкап камер, групп и раскладок. Пароли камер не включаются.',
  'System.Imported': 'Импортировано:',
  'System.ImportError': 'Импорт не удался — проверьте файл.',
  'System.SessionsTitle': 'Сессии',
  'System.RevokeAll': 'Завершить все сессии',
  'System.RevokeConfirm': 'Завершить все сессии, включая текущую?',

  'Cameras.Title': 'Камеры',
  'Cameras.Add': '＋ Добавить камеру',
  'Cameras.Empty': 'Камер пока нет.',
  'Common.Loading': 'Загрузка…',
  'Common.Save': 'Сохранить',
  'Common.Cancel': 'Отмена',
  'Common.Close': 'Закрыть',
  'Cameras.Th.Name': 'Имя',
  'Cameras.Th.Host': 'Хост',
  'Cameras.Th.Group': 'Группа',
  'Cameras.Th.Grid': 'Сетка',
  'Cameras.Live': '▶ Эфир',
  'Cameras.Edit': 'Изменить',
  'Cameras.Delete': 'Удалить',
  'Cameras.DeleteConfirm': 'Удалить камеру?',
  'Common.Yes': 'да',
  'Common.No': 'нет',

  'Editor.AddTitle': 'Добавить камеру',
  'Editor.EditTitle': 'Изменить камеру',
  'Editor.Error': 'Проверьте поля — нужны имя, хост и корректный RTSP URL.',
  'Editor.Name': 'Имя',
  'Editor.Host': 'Хост',
  'Editor.RtspMain': 'RTSP main URL',
  'Editor.RtspSub': 'RTSP sub URL (необязательно)',
  'Editor.HttpPort': 'HTTP-порт',
  'Editor.OnvifPort': 'ONVIF-порт',
  'Editor.Group': 'Группа',
  'Editor.NoGroup': '(без группы)',
  'Editor.Quality': 'Качество потока',
  'Editor.Username': 'Логин',
  'Editor.Password': 'Пароль',
  'Editor.KeepBlank': 'пусто = не менять',
  'Editor.Optional': 'необязательно',
  'Editor.Save': 'Сохранить',
  'Editor.Add': 'Добавить камеру',
  'Editor.Cancel': 'Отмена',

  'Grid.Title': 'Сетка',
  'Grid.Empty': 'Нет камер для показа. Добавьте камеры или включите их в сетку.',
  'Grid.NewLayout': '＋ Раскладка',
  'Grid.NewLayoutTitle': 'Новая раскладка',
  'Grid.NewLayoutName': 'Название новой раскладки',
  'Grid.Edit': 'Изменить раскладку',
  'Grid.Rename': 'Переименовать',
  'Grid.DeleteLayout': 'Удалить раскладку',
  'Grid.DeleteLayoutConfirm': 'Удалить эту раскладку?',
  'Grid.Size': 'Размер',
  'Grid.EmptyCell': '(пусто)',
  'Grid.NoLayouts': 'Раскладок пока нет — создайте.',
  'Grid.Single': 'Одна камера',
  'Grid.PrevPage': 'Предыдущая страница',
  'Grid.NextPage': 'Следующая страница',
  'Grid.EditingPage': 'Редактируется страница',

  'Groups.Title': 'Группы',
  'Groups.Add': '＋ Добавить группу',
  'Groups.Name': 'Имя',
  'Groups.NewName': 'Название группы',
  'Groups.Empty': 'Групп пока нет.',
  'Groups.Rename': 'Переименовать группу',
  'Groups.DeleteConfirm': 'Удалить группу?',
  'Groups.InUse': 'Группа ещё используется камерами.',
  'System.Account': 'Учётная запись',

  'Live.Back': '← Камеры',
  'Camera.Details': 'Детали',
  'Camera.Credentials': 'Учётные данные заданы',
  'Camera.Capabilities': 'Возможности',
  'Camera.Chip': 'Чип',
  'Camera.Firmware': 'Прошивка',

  'Ptz.Title': 'Управление PTZ',
  'Ptz.Up': 'Вверх',
  'Ptz.Down': 'Вниз',
  'Ptz.Left': 'Влево',
  'Ptz.Right': 'Вправо',
  'Ptz.UpLeft': 'Вверх-влево',
  'Ptz.UpRight': 'Вверх-вправо',
  'Ptz.DownLeft': 'Вниз-влево',
  'Ptz.DownRight': 'Вниз-вправо',
  'Ptz.Stop': 'Стоп',
  'Ptz.Zoom': 'Зум',
  'Ptz.ZoomIn': 'Приблизить',
  'Ptz.ZoomOut': 'Отдалить',
  'Ptz.Speed': 'Скорость',
  'Ptz.Presets': 'Пресеты',
  'Ptz.PresetName': 'Новый пресет',
  'Ptz.PresetSave': 'Сохранить',
  'Ptz.PresetDelete': 'Удалить пресет',
  'Ptz.Error': 'Камера не приняла команду PTZ.',

  'Discovery.Title': 'Поиск камер',
  'Discovery.Scan': 'Искать',
  'Discovery.Stop': 'Стоп',
  'Discovery.DeepScan': 'Глубокий скан',
  'Discovery.DeepScanNote':
    'Пассивные источники (ONVIF, mDNS) работают всегда. Глубокий скан дополнительно обходит подсеть — найдёт камеры, которые о себе не заявляют, но со стороны выглядит как сканирование портов.',
  'Discovery.Scanning': 'Идёт поиск…',
  'Discovery.Found': 'Найдено:',
  'Discovery.Nothing': 'Никто не ответил. Попробуйте глубокий скан или добавьте камеру вручную.',
  'Discovery.Cancelled': 'Поиск отменён.',
  'Discovery.Failed': 'Поиск не удался.',
  'Discovery.Busy': 'Поиск уже идёт.',
  'Discovery.Th.Device': 'Устройство',
  'Discovery.Th.Host': 'Адрес',
  'Discovery.Th.Signals': 'Как найдено',
  'Discovery.Confidence.High': 'опознана',
  'Discovery.Confidence.Medium': 'скорее всего камера',
  'Discovery.Confidence.Low': 'возможно',
  'Discovery.AlreadyAdded': 'уже добавлена',
  'Discovery.Add': 'Добавить',
  'Discovery.AddTitle': 'Добавить камеру',
  'Discovery.Probe': 'Опросить',
  'Discovery.ProbeFirst': 'опросите камеру или впишите RTSP URL',
  'Discovery.ProbeFailed': 'Опрос не удался.',
  'Discovery.NoOnvif': 'ONVIF не ответил — проверьте логин или добавьте камеру по RTSP URL ниже.',
  'Discovery.AddFailed': 'Не удалось добавить камеру.',
}
