// EN/RU strings for the React SPA — ported from the Phase 20 WebStrings.cs, plus
// a handful of new keys for the client-only bits (Groups CRUD, in-place toasts).
// Keep in sync with the backend set where they overlap.
type Dict = Record<string, string>

export const EN: Dict = {
  'Login.Subtitle': 'Sign in to the web console',
  'Login.Username': 'Username',
  'Login.Password': 'Password',
  'Login.SignIn': 'Sign in',
  'Login.Error': 'Invalid username or password.',

  'Nav.Cameras': 'Cameras',
  'Nav.Grid': 'Grid',
  'Nav.Groups': 'Groups',
  'Nav.System': 'System',
  'Nav.SignOut': 'Sign out',

  'System.Title': 'System',
  'System.Version': 'Version',
  'System.Cameras': 'Cameras',
  'System.Groups': 'Groups',
  'System.Sessions': 'Active sessions',
  'System.Streams': 'Live streams',
  'System.Backup': 'Backup & restore',
  'System.Export': '⭳ Export config',
  'System.ImportBtn': 'Import',
  'System.BackupNote':
    'Export writes a JSON backup of cameras, groups and layouts. Camera passwords are never included.',
  'System.Imported': 'Imported:',
  'System.ImportError': 'Import failed — check the file.',
  'System.SessionsTitle': 'Sessions',
  'System.RevokeAll': 'Sign out all sessions',
  'System.RevokeConfirm': 'Sign out every session, including this one?',

  'Cameras.Title': 'Cameras',
  'Cameras.Add': '＋ Add camera',
  'Cameras.Empty': 'No cameras yet.',
  'Common.Loading': 'Loading…',
  'Common.Save': 'Save',
  'Common.Cancel': 'Cancel',
  'Common.Close': 'Close',
  'Cameras.Th.Name': 'Name',
  'Cameras.Th.Host': 'Host',
  'Cameras.Th.Group': 'Group',
  'Cameras.Th.Grid': 'Grid',
  'Cameras.Live': '▶ Live',
  'Cameras.Edit': 'Edit',
  'Cameras.Delete': 'Delete',
  'Cameras.DeleteConfirm': 'Delete this camera?',
  'Common.Yes': 'yes',
  'Common.No': 'no',

  'Editor.AddTitle': 'Add camera',
  'Editor.EditTitle': 'Edit camera',
  'Editor.Error':
    'Please check the fields — name, host and a valid RTSP URL are required.',
  'Editor.Name': 'Name',
  'Editor.Host': 'Host',
  'Editor.RtspMain': 'RTSP main URL',
  'Editor.RtspSub': 'RTSP sub URL (optional)',
  'Editor.HttpPort': 'HTTP port',
  'Editor.OnvifPort': 'ONVIF port',
  'Editor.Group': 'Group',
  'Editor.NoGroup': '(no group)',
  'Editor.Quality': 'Stream quality',
  'Editor.Username': 'Username',
  'Editor.Password': 'Password',
  'Editor.KeepBlank': 'leave blank to keep',
  'Editor.Optional': 'optional',
  'Editor.Save': 'Save',
  'Editor.Add': 'Add camera',
  'Editor.Cancel': 'Cancel',

  'Grid.Title': 'Grid',
  'Grid.Empty': 'No cameras to show. Add cameras or include them in the grid.',
  'Grid.NewLayout': '＋ Layout',
  'Grid.NewLayoutTitle': 'New layout',
  'Grid.NewLayoutName': 'New layout name',
  'Grid.Edit': 'Edit layout',
  'Grid.Rename': 'Rename',
  'Grid.DeleteLayout': 'Delete layout',
  'Grid.DeleteLayoutConfirm': 'Delete this layout?',
  'Grid.Size': 'Size',
  'Grid.EmptyCell': '(empty)',
  'Grid.NoLayouts': 'No layouts yet — create one.',
  'Grid.Single': 'Single camera',

  'Groups.Title': 'Groups',
  'Groups.Add': '＋ Add group',
  'Groups.Name': 'Name',
  'Groups.NewName': 'Group name',
  'Groups.Empty': 'No groups yet.',
  'Groups.Rename': 'Rename group',
  'Groups.DeleteConfirm': 'Delete this group?',
  'Groups.InUse': 'Group is still used by cameras.',
  'System.Account': 'Account',

  'Live.Back': '← Cameras',
  'Camera.Details': 'Details',
  'Camera.Credentials': 'Credentials set',
  'Camera.Capabilities': 'Capabilities',
  'Camera.Chip': 'Chip',
  'Camera.Firmware': 'Firmware',
}

export const RU: Dict = {
  'Login.Subtitle': 'Вход в веб-консоль',
  'Login.Username': 'Логин',
  'Login.Password': 'Пароль',
  'Login.SignIn': 'Войти',
  'Login.Error': 'Неверный логин или пароль.',

  'Nav.Cameras': 'Камеры',
  'Nav.Grid': 'Сетка',
  'Nav.Groups': 'Группы',
  'Nav.System': 'Система',
  'Nav.SignOut': 'Выход',

  'System.Title': 'Система',
  'System.Version': 'Версия',
  'System.Cameras': 'Камеры',
  'System.Groups': 'Группы',
  'System.Sessions': 'Активные сессии',
  'System.Streams': 'Живые потоки',
  'System.Backup': 'Бэкап и восстановление',
  'System.Export': '⭳ Экспорт конфига',
  'System.ImportBtn': 'Импорт',
  'System.BackupNote':
    'Экспорт пишет JSON-бэкап камер, групп и раскладок. Пароли камер не включаются.',
  'System.Imported': 'Импортировано:',
  'System.ImportError': 'Импорт не удался — проверьте файл.',
  'System.SessionsTitle': 'Сессии',
  'System.RevokeAll': 'Завершить все сессии',
  'System.RevokeConfirm': 'Завершить все сессии, включая текущую?',

  'Cameras.Title': 'Камеры',
  'Cameras.Add': '＋ Добавить камеру',
  'Cameras.Empty': 'Камер пока нет.',
  'Common.Loading': 'Загрузка…',
  'Common.Save': 'Сохранить',
  'Common.Cancel': 'Отмена',
  'Common.Close': 'Закрыть',
  'Cameras.Th.Name': 'Имя',
  'Cameras.Th.Host': 'Хост',
  'Cameras.Th.Group': 'Группа',
  'Cameras.Th.Grid': 'Сетка',
  'Cameras.Live': '▶ Эфир',
  'Cameras.Edit': 'Изменить',
  'Cameras.Delete': 'Удалить',
  'Cameras.DeleteConfirm': 'Удалить камеру?',
  'Common.Yes': 'да',
  'Common.No': 'нет',

  'Editor.AddTitle': 'Добавить камеру',
  'Editor.EditTitle': 'Изменить камеру',
  'Editor.Error': 'Проверьте поля — нужны имя, хост и корректный RTSP URL.',
  'Editor.Name': 'Имя',
  'Editor.Host': 'Хост',
  'Editor.RtspMain': 'RTSP main URL',
  'Editor.RtspSub': 'RTSP sub URL (необязательно)',
  'Editor.HttpPort': 'HTTP-порт',
  'Editor.OnvifPort': 'ONVIF-порт',
  'Editor.Group': 'Группа',
  'Editor.NoGroup': '(без группы)',
  'Editor.Quality': 'Качество потока',
  'Editor.Username': 'Логин',
  'Editor.Password': 'Пароль',
  'Editor.KeepBlank': 'пусто = не менять',
  'Editor.Optional': 'необязательно',
  'Editor.Save': 'Сохранить',
  'Editor.Add': 'Добавить камеру',
  'Editor.Cancel': 'Отмена',

  'Grid.Title': 'Сетка',
  'Grid.Empty': 'Нет камер для показа. Добавьте камеры или включите их в сетку.',
  'Grid.NewLayout': '＋ Раскладка',
  'Grid.NewLayoutTitle': 'Новая раскладка',
  'Grid.NewLayoutName': 'Название новой раскладки',
  'Grid.Edit': 'Изменить раскладку',
  'Grid.Rename': 'Переименовать',
  'Grid.DeleteLayout': 'Удалить раскладку',
  'Grid.DeleteLayoutConfirm': 'Удалить эту раскладку?',
  'Grid.Size': 'Размер',
  'Grid.EmptyCell': '(пусто)',
  'Grid.NoLayouts': 'Раскладок пока нет — создайте.',
  'Grid.Single': 'Одна камера',

  'Groups.Title': 'Группы',
  'Groups.Add': '＋ Добавить группу',
  'Groups.Name': 'Имя',
  'Groups.NewName': 'Название группы',
  'Groups.Empty': 'Групп пока нет.',
  'Groups.Rename': 'Переименовать группу',
  'Groups.DeleteConfirm': 'Удалить группу?',
  'Groups.InUse': 'Группа ещё используется камерами.',
  'System.Account': 'Учётная запись',

  'Live.Back': '← Камеры',
  'Camera.Details': 'Детали',
  'Camera.Credentials': 'Учётные данные заданы',
  'Camera.Capabilities': 'Возможности',
  'Camera.Chip': 'Чип',
  'Camera.Firmware': 'Прошивка',
}
